sequenceDiagram
    participant CM as Client Manager<br/>(User Space)
    participant StartMap as manager_start_map
    participant TidMap as active_exec_id_map
    participant LatMap as manager_lat_map

    Note over CM: [uprobe] process_client_request
    CM->>StartMap: Save CM Start Time (key: exec_id)
    
    Note over CM: [uprobe] handle_execution_response
    CM->>TidMap: Save active exec_id (key: TID)
    
    Note over CM: [uretprobe] handle_execution_response_ret
    TidMap-->>CM: Read & Delete active exec_id (key: TID)
    StartMap-->>CM: Read & Delete CM Start Time (key: exec_id)
    CM->>LatMap: Save CM Latency (key: exec_id)
